### PR TITLE
Fix main branch tests

### LINKED ISSUE #631: Fix the broken main branch CI
The CI failing on PR: https://github.com/astronomer/dag-factory/pull/627

Logs
```
warning: The `tool.uv.dev-dependencies` field (used in `pyproject.toml`) is deprecated and will be removed in a future release; use `dependency-groups.dev` instead
Using Python 3.10.19 environment at: /home/runner/.local/share/hatch/env/virtual/dag-factory/onaeQMJR/tests.py3.10-2.4
Resolved 1 package in 12ms
Prepared 1 package in 4ms
Uninstalled 1 package in 0.35ms
Installed 1 package in 2ms
Bytecode compiled 5853 files in 247ms
 - tabulate==0.8.10
 + tabulate==0.9.0
+ pytest -vv --cov=dagfactory --cov-report=term-missing --cov-report=xml -m integration
scripts/test/integration.sh: 17: pytest: not found
Error: Process completed with exit code 127.
```
https://github.com/astronomer/dag-factory/actions/runs/19895123213/job/57219267453?pr=627

### PR DESCRIPTION
**Pull request by tatiana**
DAG Factory was installing Airlfow dependencies in inconsistent ways (after having installed Airflow, we were installing Airflow providers without using uv and without constraints), which led some tests to fail because the wrong version of Airflow was installed, as observed in:
```
../../../.local/share/hatch/env/virtual/dag-factory/onaeQMJR/tests.py3.10-2.6/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:197: in exec_module
    exec(co, module.__dict__)
tests/test_utils.py:8: in <module>
    from dagfactory import utils
dagfactory/__init__.py:3: in <module>
    from .dagfactory import load_yaml_dags
dagfactory/dagfactory.py:10: in <module>
    from airflow.configuration import conf as airflow_conf
E   ModuleNotFoundError: No module named 'airflow.configuration'
```
https://github.com/astronomer/dag-factory/actions/runs/20233525086/job/58082152561?pr=636

Which was meant to run with `apache-airflow==2.6.0` but were run with `apache-airflow==3.1.5`.

Closes: #631

### CODE REVIEW

File: scripts/test/pre-install-airflow.sh [hunk 1]
```diff
@@ -33,11 +33,15 @@ uv pip install pip --upgrade
...
-  uv pip install "apache-airflow>=3.0.2" --constraint /tmp/constraint.txt
+  uv pip install "apache-airflow~=3.0.2" --constraint /tmp/constraint.txt
 else
   uv pip install "apache-airflow==$AIRFLOW_VERSION" --constraint /tmp/constraint.txt
 fi;
 
+# Install dag-factory and test dependencies with the same constraints
+uv pip install --constraint /tmp/constraint.txt -e .
+uv pip install --constraint /tmp/constraint.txt apache-airflow-providers-http>=4.0.0 apache-airflow-providers-cncf-kubernetes>=4.4.0 apache-airflow-providers-common-sql>=1.2.0 apache-airflow-providers-slack pytest>=6.0 pytest-cov pre-commit httpx>=0.25.0 pandas
+
```
Comment (tatiana) [inline scripts/test/pre-install-airflow.sh]:
```suggestion
```

File: pyproject.toml [hunk 2]
```diff
@@ -107,12 +106,7 @@ compile-bytecode = true
 ######################################
 
 [tool.hatch.envs.tests]
-dependencies = [
-    "dag-factory[tests]",
-    "apache-airflow~={matrix:airflow}.0,!=2.9.0,!=2.9.1",  # https://github.com/apache/airflow/pull/39670
-    "httpx>=0.25.0",
-    "pandas",
-]
+dependencies = []
```
Comment (tatiana) [inline pyproject.toml]:
```suggestion
dependencies = [
    "dag-factory[tests]"
]
```

File: tests/test_dagbuilder.py [hunk 3]
```diff
@@ -798,7 +798,7 @@ def test_make_dag_with_callbacks():
     assert dag.on_failure_callback.__name__ == "print_context_callback"
 
     # sla_miss_callback is removed as of Airflow 3.1.0
-    if version.parse("2.6.0") <= version.parse(AIRFLOW_VERSION) < version.parse("3.1.0"):
+    if version.parse("2.6.0") < version.parse(AIRFLOW_VERSION) < version.parse("3.1.0"):
```
Comment (pankajkoti) [inline tests/test_dagbuilder.py:801]: Why this change?

**Review by pankajkoti — APPROVED** [review]
LGTM. Have 1 question inline

File: tests/test_dagbuilder.py (hunk 3 above)
Comment (tatiana) [reply tests/test_dagbuilder.py:801]: Because there is an incompatible version of Slack being installed with Airflow 2.6.0 in the CI, and since the tests were already very restrictively for old versions, I thought we could just drop testing with AF 2.6

Comment (pankajkoti) [reply tests/test_dagbuilder.py:801]: okay, let's also think about dropping support for Airflow < 2.7 in DAG Factory
